spring.profiles.active=dev

# =========================
# SERVER (INSIDE CONTAINER)
# =========================
server.port=8081

# =========================
# H2 CONSOLE
# =========================
spring.h2.console.enabled=true

# =========================
# H2 DATABASE
# =========================
spring.datasource.url=jdbc:h2:file:~/binarybrainscovid;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update

# =========================
# SECURITY
# =========================
token.secret=10d73c0906053a33e5b96500d7c5eeaf717f199a54c5baff4d7da9d0b0

server.error.include-message=always

app.testrun=false

spring.jackson.serialization.fail-on-empty-beans=false

# =========================
# MULTIPART CONFIG
# =========================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

# =========================
# FILE STORAGE
# =========================
file.upload-dir=useruploads